# Generated by Django 5.1.7 on 2025-07-05 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('bsns_name', models.CharField(max_length=255)),
                ('bsns_address', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('mall', 'Mall'), ('restaurant', 'Restaurant'), ('school', 'School'), ('hospital', 'Hospital'), ('office', 'Office'), ('market', 'Market'), ('other', 'Other')], default='other', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('archived', 'Archived')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Investible',
            fields=[
                ('investible_id', models.AutoField(primary_key=True, serialize=False)),
                ('invst_location', models.CharField(max_length=255)),
                ('invst_description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], default='available', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='password', max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], max_length=10)),
                ('user_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('archive', 'Archive')], default='online', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('marker_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_markers', to='api.business')),
                ('invst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_markers', to='api.investible')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_description', models.TextField()),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.business')),
                ('investible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.investible')),
            ],
        ),
    ]
