# Generated by Django 5.1.7 on 2025-07-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
