# Generated by Django 5.1.7 on 2025-07-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('active', 'Active'), ('archive', 'Archive')], default='active', max_length=8),
        ),
    ]
