# Generated by Django 5.1.7 on 2025-07-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_user_role_alter_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='Employee', max_length=10),
        ),
    ]
