# Generated by Django 5.2.3 on 2025-06-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('bsns_name', models.CharField(max_length=255)),
                ('bsns_address', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Investible',
            fields=[
                ('investible_id', models.AutoField(primary_key=True, serialize=False)),
                ('invst_location', models.CharField(max_length=255)),
                ('invst_description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('user_role', models.CharField(blank=True, max_length=30)),
                ('user_status', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=255)),
                ('loc_address', models.CharField(max_length=255)),
                ('loc_type', models.CharField(max_length=50)),
                ('bsns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='api.business')),
                ('invst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='api.investible')),
            ],
        ),
    ]
