# Generated by Django 5.1.7 on 2025-06-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loc_type',
            new_name='mrk_type',
        ),
    ]
