# Generated by Django 5.1.7 on 2025-06-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_loc_type_location_mrk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], max_length=10),
        ),
    ]
