# Generated by Django 5.1.7 on 2025-06-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_id',
            new_name='mrk_location_id',
        ),
    ]
