# Generated by Django 5.1.7 on 2025-07-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_marker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
