# Generated by Django 5.1.7 on 2025-07-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_markers', to='api.business'),
        ),
        migrations.AddField(
            model_name='marker',
            name='invst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_markers', to='api.investible'),
        ),
    ]
