# Generated by Django 5.1.7 on 2025-07-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_marker_business_marker_invst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
    ]
