# Generated by Django 5.1.7 on 2025-07-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='business',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='invst',
        ),
    ]
