# Generated by Django 5.1.7 on 2025-07-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_marker_business_remove_marker_invst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_description', models.TextField()),
                ('report_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
