# Generated by Django 5.1.7 on 2025-07-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_report_business_report_investible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='marker_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
