# Generated by Django 5.1.7 on 2025-07-03 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_marker_marker_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='id',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='location',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='marker_type',
        ),
        migrations.AddField(
            model_name='marker',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_markers', to='api.business'),
        ),
        migrations.AddField(
            model_name='marker',
            name='invst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_markers', to='api.investible'),
        ),
        migrations.AddField(
            model_name='marker',
            name='marker_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
