# Generated by Django 5.1.7 on 2025-07-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_marker_id_remove_marker_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bsns_type',
            field=models.CharField(choices=[('mall', 'Mall'), ('restaurant', 'Restaurant'), ('school', 'School'), ('hospital', 'Hospital'), ('office', 'Office'), ('market', 'Market'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
