# Generated by Django 5.1.7 on 2025-07-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_business_bsns_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='bsns_type',
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(choices=[('mall', 'Mall'), ('restaurant', 'Restaurant'), ('school', 'School'), ('hospital', 'Hospital'), ('office', 'Office'), ('market', 'Market'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
